# Generated by Django 2.2.6 on 2019-10-17 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_curso', models.CharField(max_length=10)),
                ('cod_disciplina', models.CharField(max_length=10)),
                ('dt_ini', models.DateTimeField(blank=True, null=True)),
                ('dt_fim', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=1000)),
                ('tipoResposta', models.CharField(choices=[('DC', 'Descritiva'), ('ME', 'Múltipla Escolha'), ('CS', 'Caixa de Seleção')], default='ME', max_length=2)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avalPosApp.Avaliacao')),
            ],
        ),
    ]
