# Generated by Django 2.2.6 on 2019-10-17 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avalPosApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('cod', models.CharField(default='ABC123', max_length=10, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='autor',
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='dt_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='dt_ini',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio'),
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('cod', models.CharField(default='ABC123', max_length=10, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=250, null=True)),
                ('cod_curso', models.ForeignKey(default='ABC123', on_delete=django.db.models.deletion.CASCADE, to='avalPosApp.Curso')),
            ],
        ),
    ]
