# Generated by Django 2.2.6 on 2019-10-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalPosApp', '0002_auto_20191017_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='cod',
            field=models.CharField(default='ABC123', max_length=10, primary_key=True, serialize=False, verbose_name='Codigo Curso'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='cod',
            field=models.CharField(default='ABC123', max_length=10, primary_key=True, serialize=False, verbose_name='Codigo Disciplina'),
        ),
    ]
