# Generated by Django 2.2.6 on 2019-10-17 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avalPosApp', '0004_auto_20191017_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=1000)),
                ('cod_pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avalPosApp.Pergunta')),
            ],
        ),
    ]
