# Generated by Django 2.2.6 on 2019-10-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avalPosApp', '0005_resposta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='cod_curso',
        ),
    ]
