# Generated by Django 2.2.6 on 2019-10-21 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avalPosApp', '0007_avaliacao_respostas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoRespostas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=1000)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tipoResposta', models.CharField(choices=[('DC', 'Descritiva'), ('ME', 'Múltipla Escolha'), ('CS', 'Caixa de Seleção')], default='ME', max_length=2)),
                ('cod_pergunta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avalPosApp.Pergunta')),
            ],
        ),
        migrations.DeleteModel(
            name='Avaliacao_Respostas',
        ),
    ]
