# Generated by Django 2.2.6 on 2019-10-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalPosApp', '0008_auto_20191021_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
