# Generated by Django 2.2.6 on 2019-10-21 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avalPosApp', '0010_auto_20191021_1610'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvaliacaoRespostas',
            new_name='AvaliacaoResposta',
        ),
    ]
