# Generated by Django 2.2.6 on 2019-10-21 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avalPosApp', '0011_auto_20191021_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacaoresposta',
            name='resposta',
        ),
        migrations.RemoveField(
            model_name='avaliacaoresposta',
            name='tipoResposta',
        ),
        migrations.AlterField(
            model_name='avaliacaoresposta',
            name='cod_pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avalPosApp.Pergunta'),
        ),
    ]
