# Generated by Django 2.2.6 on 2019-10-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalPosApp', '0012_auto_20191021_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaoresposta',
            name='resposta',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
