# Generated by Django 2.2.6 on 2019-10-21 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avalPosApp', '0013_avaliacaoresposta_resposta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacaoresposta',
            name='resposta',
        ),
    ]
