# Generated by Django 2.2.6 on 2019-10-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalPosApp', '0014_remove_avaliacaoresposta_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='resposta_user',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
