# Generated by Django 2.2.6 on 2019-10-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalPosApp', '0016_auto_20191022_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='cod_pergunta',
            field=models.IntegerField(),
        ),
    ]
