# Generated by Django 2.2.6 on 2019-10-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalPosApp', '0018_auto_20191022_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaoresposta',
            name='cod_avaliacao',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacaoresposta',
            name='cod_curso',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacaoresposta',
            name='cod_disciplina',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
