# Generated by Django 2.2.6 on 2019-10-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalPosApp', '0019_auto_20191022_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacaoresposta',
            old_name='texto',
            new_name='texto_pergunta',
        ),
        migrations.RemoveField(
            model_name='avaliacaoresposta',
            name='resposta_conteudo',
        ),
        migrations.AddField(
            model_name='avaliacaoresposta',
            name='texto_resposta',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
