# Generated by Django 2.2.6 on 2019-10-24 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avalPosApp', '0023_auto_20191023_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pergunta',
            old_name='tipoResposta',
            new_name='tipo_resposta',
        ),
    ]
