# Generated by Django 2.2.6 on 2019-10-24 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avalPosApp', '0024_auto_20191024_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='cod_disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avalPosApp.Disciplina'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='cod',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código Curso'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='cod',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código Disciplina'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='cod_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avalPosApp.Curso'),
        ),
        migrations.DeleteModel(
            name='Opcao',
        ),
    ]
