# Generated by Django 2.2.6 on 2019-10-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalPosApp', '0026_auto_20191024_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostaopcao',
            name='pergunta',
            field=models.ManyToManyField(to='avalPosApp.Pergunta'),
        ),
    ]
