# Generated by Django 2.2.6 on 2019-10-24 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avalPosApp', '0028_perguntarespostaopcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaopergunta',
            name='cod_pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avalPosApp.Pergunta', unique=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='texto',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='respostaopcao',
            name='texto',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='avaliacaopergunta',
            unique_together={('cod_avaliacao', 'cod_pergunta')},
        ),
        migrations.AlterUniqueTogether(
            name='perguntarespostaopcao',
            unique_together={('cod_pergunta', 'cod_resposta_opcao')},
        ),
    ]
