# Generated by Django 2.2.6 on 2019-10-24 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avalPosApp', '0030_auto_20191024_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaopergunta',
            name='cod_pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avalPosApp.Pergunta'),
        ),
    ]
