# Generated by Django 2.2.6 on 2019-10-25 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avalPosApp', '0031_auto_20191024_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='timestamp',
        ),
        migrations.CreateModel(
            name='AvaliacaoDisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avalPosApp.Avaliacao')),
                ('cod_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avalPosApp.Disciplina')),
            ],
            options={
                'unique_together': {('cod_avaliacao', 'cod_disciplina')},
            },
        ),
    ]
