# Generated by Django 2.2.6 on 2019-10-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalPosApp', '0032_auto_20191025_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='cod_disciplina',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='descricao',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descrição'),
        ),
    ]
