# Generated by Django 2.2.6 on 2019-10-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalPosApp', '0033_auto_20191025_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='descricao',
            field=models.CharField(default=1, max_length=1000, verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
