# Generated by Django 2.2.6 on 2019-10-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalPosApp', '0035_avaliacao_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
