# Generated by Django 2.2.6 on 2019-10-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avalPosApp', '0036_auto_20191025_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacaodisciplina',
            old_name='cod_avaliacao',
            new_name='avaliacao',
        ),
        migrations.RenameField(
            model_name='avaliacaodisciplina',
            old_name='cod_disciplina',
            new_name='disciplina',
        ),
        migrations.RenameField(
            model_name='avaliacaopergunta',
            old_name='cod_avaliacao',
            new_name='avaliacao',
        ),
        migrations.RenameField(
            model_name='avaliacaopergunta',
            old_name='cod_pergunta',
            new_name='pergunta',
        ),
        migrations.RenameField(
            model_name='perguntarespostaopcao',
            old_name='cod_pergunta',
            new_name='pergunta',
        ),
        migrations.RenameField(
            model_name='perguntarespostaopcao',
            old_name='cod_resposta_opcao',
            new_name='resposta_opcao',
        ),
        migrations.AlterUniqueTogether(
            name='avaliacaodisciplina',
            unique_together={('avaliacao', 'disciplina')},
        ),
        migrations.AlterUniqueTogether(
            name='avaliacaopergunta',
            unique_together={('avaliacao', 'pergunta')},
        ),
        migrations.AlterUniqueTogether(
            name='perguntarespostaopcao',
            unique_together={('pergunta', 'resposta_opcao')},
        ),
    ]
