# Generated by Django 2.2.6 on 2019-10-25 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avalPosApp', '0037_auto_20191025_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacaoRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_avaliacao', models.CharField(max_length=100)),
                ('cod_avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avalPosApp.Avaliacao')),
            ],
        ),
    ]
