# Generated by Django 2.2.6 on 2019-10-25 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avalPosApp', '0038_aplicacaoregistro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApliccaoResposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_pergunta', models.IntegerField()),
                ('texto_pergunta', models.CharField(max_length=1000)),
                ('texto_resposta', models.CharField(max_length=1000)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avalPosApp.AplicacaoRegistro')),
            ],
        ),
    ]
