# Generated by Django 2.2.6 on 2019-10-25 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avalPosApp', '0039_apliccaoresposta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacaoresposta',
            name='id_registro',
        ),
        migrations.DeleteModel(
            name='AvaliacaoRegistro',
        ),
        migrations.DeleteModel(
            name='AvaliacaoResposta',
        ),
    ]
