# Generated by Django 2.2.6 on 2019-10-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avalPosApp', '0040_auto_20191025_1558'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApliccaoResposta',
            new_name='AplicacaoResposta',
        ),
    ]
