# Generated by Django 2.2.6 on 2019-10-25 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avalPosApp', '0043_auto_20191025_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacaoregistro',
            name='disciplina',
            field=models.ForeignKey(default="DISC001", on_delete=django.db.models.deletion.CASCADE, to='avalPosApp.Disciplina'),
            preserve_default=False,
        ),
    ]
